rm -rf out/production
rm -f com/pdfjet/*.class
rm -f net/pdfjet/*.exe.mdb
rm -f examples/*.class
rm -f examples/*.exe.mdb
rm -f tests/*.exe.mdb
rm -f util/*.class
rm -f *.jar
rm -f *.exe
rm -f *.mdb
rm -f *.dll
rm -rf bin
rm -rf obj
rm -rf .build
rm -f *.pdf
