// swift-tools-version:5.2

import PackageDescription

let package = Package(
    name: "PDFjet",
    targets: [
        .target(name: "Example_01", dependencies: ["PDFjet"]),
        .target(name: "Example_02", dependencies: ["PDFjet"]),
        .target(name: "Example_03", dependencies: ["PDFjet"]),
        .target(name: "Example_04", dependencies: ["PDFjet"]),
        .target(name: "Example_05", dependencies: ["PDFjet"]),
        .target(name: "Example_06", dependencies: ["PDFjet"]),
        .target(name: "Example_07", dependencies: ["PDFjet"]),
        .target(name: "Example_08", dependencies: ["PDFjet"]),
        .target(name: "Example_09", dependencies: ["PDFjet"]),
        .target(name: "Example_10", dependencies: ["PDFjet"]),
        .target(name: "Example_11", dependencies: ["PDFjet"]),
        .target(name: "Example_12", dependencies: ["PDFjet"]),
        .target(name: "Example_13", dependencies: ["PDFjet"]),
        .target(name: "Example_14", dependencies: ["PDFjet"]),
        .target(name: "Example_15", dependencies: ["PDFjet"]),
        .target(name: "Example_16", dependencies: ["PDFjet"]),
        .target(name: "Example_17", dependencies: ["PDFjet"]),
        .target(name: "Example_18", dependencies: ["PDFjet"]),
        .target(name: "Example_19", dependencies: ["PDFjet"]),
        .target(name: "Example_20", dependencies: ["PDFjet"]),
        .target(name: "Example_21", dependencies: ["PDFjet"]),
        .target(name: "Example_22", dependencies: ["PDFjet"]),
        .target(name: "Example_23", dependencies: ["PDFjet"]),
        .target(name: "Example_24", dependencies: ["PDFjet"]),
        .target(name: "Example_25", dependencies: ["PDFjet"]),
        .target(name: "Example_26", dependencies: ["PDFjet"]),
        .target(name: "Example_27", dependencies: ["PDFjet"]),
        .target(name: "Example_28", dependencies: ["PDFjet"]),
        .target(name: "Example_29", dependencies: ["PDFjet"]),
        .target(name: "Example_30", dependencies: ["PDFjet"]),
        .target(name: "Example_31", dependencies: ["PDFjet"]),
        .target(name: "Example_32", dependencies: ["PDFjet"]),
        .target(name: "Example_33", dependencies: ["PDFjet"]),
        .target(name: "Example_34", dependencies: ["PDFjet"]),
        .target(name: "Example_35", dependencies: ["PDFjet"]),
        .target(name: "Example_36", dependencies: ["PDFjet"]),
        .target(name: "Example_37", dependencies: ["PDFjet"]),
        .target(name: "Example_38", dependencies: ["PDFjet"]),
        .target(name: "Example_39", dependencies: ["PDFjet"]),
        .target(name: "Example_40", dependencies: ["PDFjet"]),
        .target(name: "Example_41", dependencies: ["PDFjet"]),
        .target(name: "Example_42", dependencies: ["PDFjet"]),
        .target(name: "Example_43", dependencies: ["PDFjet"]),
        .target(name: "Example_44", dependencies: ["PDFjet"]),
        .target(name: "Example_45", dependencies: ["PDFjet"]),
        .target(name: "Example_46", dependencies: ["PDFjet"]),
        .target(name: "Example_47", dependencies: ["PDFjet"]),
        .target(name: "Example_48", dependencies: ["PDFjet"]),
        .target(name: "Example_49", dependencies: ["PDFjet"]),
        .target(name: "Example_50", dependencies: ["PDFjet"]),
        .target(name: "Example_59", dependencies: ["PDFjet"]),
        .target(name: "Example_71", dependencies: ["PDFjet"]),
        .target(name: "Example_72", dependencies: ["PDFjet"]),
        .target(name: "Example_73", dependencies: ["PDFjet"]),
        .target(name: "Example_93", dependencies: ["PDFjet"]),
        .target(name: "PDFjet")
    ]
)
