<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="net/pdfjet/*.cs" />
    <Compile Include="net/pdfjet/Barcodes/*.cs" />
    <Compile Include="net/pdfjet/QRCode/*.cs" />
    <Compile Include="net/pdfjet/DataMatrix/*.cs" />
    <Compile Include="net/pdfjet/PDF417/*.cs" />
    <Compile Include="net/pdfjet/CoreFonts/*.cs" />
    <Compile Include="net/pdfjet/Fonts/*.cs" />
    <Compile Include="net/pdfjet/Encryption/*.cs" />
  </ItemGroup>
</Project>
