import Foundation
import PDFjet

/**
 * Example_04.swift
 *
 * Demonstrates the creation of a PDF document with text in various CJK
 * (Chinese, Japanese, Korean) languages using standard font sets.
 *
 * - Remark:
 *    **Compatibility Note:** The PDF generated by this example relies on
 *    the recipient's PDF viewer having the requisite Asian font packs installed.
 *    This is typical for most modern PDF readers and web browsers. For maximum
 *    compatibility and to ensure text renders correctly for all users, embedding
 *    a font subset (e.g., using open-source fonts like NotoSans) is recommended.
 *
 * - SeeAlso: `Font`
 * - SeeAlso: `CJKFont`
 */
public class Example_04 {
    public init() throws {
        let pdf = PDF(OutputStream(toFileAtPath: "Example_04.pdf", append: false)!)

        let f0 = Font(pdf, CoreFont.COURIER)
        f0.setSize(14.0)

        // Chinese (Traditional) font
        // Uses Adobe's Ming Standard Light font (明體)
        let f1 = Font(pdf, CJKFont.ADOBE_MING_STD_LIGHT)
        f1.setSize(14.0)

        // Chinese (Simplified) font
        // Uses Adobe's Heiti SC Light font (黑体-简)
        let f2 = Font(pdf, CJKFont.ST_HEITI_SC_LIGHT)
        f2.setSize(14.0)

        // Japanese font
        // Uses Kozuka Mincho Pro VI Regular font (小塚明朝)
        let f3 = Font(pdf, CJKFont.KOZ_MIN_PRO_VI_REGULAR)
        f3.setSize(14.0)

        // Korean font
        // Uses Adobe's Myungjo Standard Medium font (명조체)
        let f4 = Font(pdf, CJKFont.ADOBE_MYUNGJO_STD_MEDIUM)
        f4.setSize(14.0)

        let page = Page(pdf, Letter.PORTRAIT)

        let x_pos: Float = 100.0
        var y_pos: Float = 100.0

        let fileName = "data/happy-new-year.txt"
        let lines = (try String(
                contentsOfFile: fileName, encoding: .utf8)).components(separatedBy: .newlines)

        let text = TextLine(f0)
        for line in lines {
            text.setText(line)
            text.setLocation(x_pos, y_pos)
            text.drawOn(page)
            if line.contains("Traditional") {
                text.setFont(f1)
            } else if line.contains("Simplified") {
                text.setFont(f2)
            } else if line.contains("Japanese") {
                text.setFont(f3)
            } else if line.contains("Korean") {
                text.setFont(f4)
            } else {
                text.setFont(f0)
            }
            y_pos += Float(25.0)
        }

        pdf.complete()
    }
}   // End of Example_04.swift

let time0 = Int64(Date().timeIntervalSince1970 * 1000)
_ = try Example_04()
let time1 = Int64(Date().timeIntervalSince1970 * 1000)
TextUtils.printDuration("Example_04", time0, time1)
