using System;
using System.IO;
using System.Diagnostics;

using PDFjet.NET;

/// <summary>
/// Demonstrates the creation of a PDF document with text in various CJK
/// (Chinese, Japanese, Korean) languages using standard font sets.
/// </summary>
/// <remarks>
/// <para>
/// <strong>Compatibility Note:</strong> The PDF generated by this example relies on
/// the recipient's PDF viewer having the requisite Asian font packs installed.
/// This is typical for most modern PDF readers and web browsers. For maximum
/// compatibility and to ensure text renders correctly for all users, embedding
/// a font subset (e.g., using open-source fonts like NotoSans) is recommended.
/// </para>
/// </remarks>
public class Example_04 {

    public Example_04() {
        // Create a new PDF document
        PDF pdf = new PDF(new BufferedStream(
                new FileStream("Example_04.pdf", FileMode.Create)));

        Font f0 = new Font(pdf, CoreFont.HELVETICA);
        f0.SetSize(14f);

        // Create font for Traditional Chinese text
        // Uses Adobe's Ming Standard Light font (明體)
        Font f1 = new Font(pdf, CJKFont.ADOBE_MING_STD_LIGHT);
        f1.SetSize(14f);

        // Create font for Simplified Chinese text
        // Uses Adobe's Heiti SC Light font (黑体-简)
        Font f2 = new Font(pdf, CJKFont.ST_HEITI_SC_LIGHT);
        f2.SetSize(14f);

        // Create font for Japanese text
        // Uses Kozuka Mincho Pro VI Regular font (小塚明朝)
        Font f3 = new Font(pdf, CJKFont.KOZ_MIN_PRO_VI_REGULAR);
        f3.SetSize(14f);

        // Create font for Korean text
        // Uses Adobe's Myungjo Standard Medium font (명조체)
        Font f4 = new Font(pdf, CJKFont.ADOBE_MYUNGJO_STD_MEDIUM);
        f4.SetSize(14f);

        Page page = new Page(pdf, Letter.PORTRAIT);

        String fileName = "data/happy-new-year.txt";
        float x_pos = 100f;
        float y_pos = 100f;
        StreamReader reader = new StreamReader(
                new FileStream(fileName, FileMode.Open, FileAccess.Read));
        TextLine text = new TextLine(f0);
        String line = null;
        while ((line = reader.ReadLine()) != null) {
            text.SetText(line);
            text.SetLocation(x_pos, y_pos);
            text.DrawOn(page);
            if (line.Contains("Traditional")) {
                text.SetFont(f1);
            } else if (line.Contains("Simplified")) {
                text.SetFont(f2);
            } else if (line.Contains("Japanese")) {
                text.SetFont(f3);
            } else if (line.Contains("Korean")) {
                text.SetFont(f4);
            } else {
                text.SetFont(f0);
            }
            y_pos += 25f;
        }
        reader.Close();

        pdf.Complete();
    }


    public static void Main(String[] args) {
        Stopwatch sw = Stopwatch.StartNew();
        long time0 = sw.ElapsedMilliseconds;
        new Example_04();
        long time1 = sw.ElapsedMilliseconds;
        TextUtils.PrintDuration("Example_04", time0, time1);
    }

}   // End of Example_04.cs
