using System;
using System.IO;
using System.Diagnostics;

using PDFjet.NET;


/**
 *  Example_04.cs
 *
 *  The PDF generated by this example program will only work with Adobe Reader 8
 *  or Foxit Reader v2.0 or higher versions. It also requires the Asian Font Packs
 *  from Adobe or Foxit Software respectively.
 */
public class Example_04 {

    public Example_04() {

        String fileName = "data/happy-new-year.txt";

        PDF pdf = new PDF(new BufferedStream(
                new FileStream("Example_04.pdf", FileMode.Create)));

        // Chinese (Traditional) font
        Font f1 = new Font(pdf, Font.AdobeMingStd_Light);

        // Chinese (Simplified) font
        Font f2 = new Font(pdf, Font.STHeitiSC_Light);

        // Japanese font
        Font f3 = new Font(pdf, Font.KozMinProVI_Regular);

        // Korean font
        Font f4 = new Font(pdf, Font.AdobeMyungjoStd_Medium);

        Page page = new Page(pdf, Letter.PORTRAIT);

        f1.SetSize(14f);
        f2.SetSize(14f);
        f3.SetSize(14f);
        f4.SetSize(14f);

        float x_pos = 100f;
        float y_pos = 100f;
        StreamReader reader = new StreamReader(
                new FileStream(fileName, FileMode.Open));
        TextLine text = new TextLine(f1);
        String line = null;
        while ((line = reader.ReadLine()) != null) {
            if (line.IndexOf("Simplified") != -1) {
                text.SetFont(f2);
            }
            else if (line.IndexOf("Japanese") != -1) {
                text.SetFont(f3);
            }
            else if (line.IndexOf("Korean") != -1) {
                text.SetFont(f4);
            }
            text.SetText(line);
            text.SetLocation(x_pos, y_pos);
            text.DrawOn(page);
            y_pos += 25f;
        }
        reader.Close();

        pdf.Complete();
    }


    public static void Main(String[] args) {
        Stopwatch sw = Stopwatch.StartNew();
        long time0 = sw.ElapsedMilliseconds;
        new Example_04();
        long time1 = sw.ElapsedMilliseconds;
        Console.WriteLine("Example_04 => " + (time1 - time0));
    }

}   // End of Example_04.cs
