package examples;

import java.io.*;

import com.pdfjet.*;


/**
 *  Example_04.java
 *
 *  The PDF generated by this example program will only work with
 *  Adobe Reader 8 or Foxit Reader v2.0 or higher versions. It also
 *  requires the Asian Font Packs from Adobe or Foxit Software respectively.
 */
public class Example_04 {

    public Example_04() throws Exception {

        String fileName = "data/happy-new-year.txt";

        PDF pdf = new PDF(
                new BufferedOutputStream(new FileOutputStream("Example_04.pdf")));

        // Chinese (Traditional) font
        Font f1 = new Font(pdf, Font.AdobeMingStd_Light);

        // Chinese (Simplified) font
        Font f2 = new Font(pdf, Font.STHeitiSC_Light);

        // Japanese font
        Font f3 = new Font(pdf, Font.KozMinProVI_Regular);

        // Korean font
        Font f4 = new Font(pdf, Font.AdobeMyungjoStd_Medium);

        Page page = new Page(pdf, Letter.PORTRAIT);

        f1.setSize(14f);
        f2.setSize(14f);
        f3.setSize(14f);
        f4.setSize(14f);

        float x_pos = 100f;
        float y_pos = 100f;
        BufferedReader reader = new BufferedReader(
                new InputStreamReader(new FileInputStream(fileName), "UTF-8"));
        TextLine text = new TextLine(f1);
        String line = null;
        while ((line = reader.readLine()) != null) {
            if (line.contains("Simplified")) {
                text.setFont(f2);
            }
            else if (line.contains("Japanese")) {
                text.setFont(f3);
            }
            else if (line.contains("Korean")) {
                text.setFont(f4);
            }
            text.setText(line);
            text.setLocation(x_pos, y_pos);
            text.drawOn(page);
            y_pos += 25f;
        }
        reader.close();

        pdf.complete();
    }


    public static void main(String[] args) throws Exception {
        long t0 = System.currentTimeMillis();
        new Example_04();
        long t1 = System.currentTimeMillis();
        System.out.println("Example_04 => " + (t1 - t0));
    }

}   // End of Example_04.java
