package examples;

import java.io.*;
import com.pdfjet.*;

/**
 * Demonstrates the creation of a PDF document with text in various CJK
 * (Chinese, Japanese, Korean) languages using standard font sets.
 * <p>
 * <strong>Compatibility Note:</strong> The PDF generated by this example relies on
 * the recipient's PDF viewer having the requisite Asian font packs installed.
 * This is typical for most modern PDF readers and web browsers. For maximum
 * compatibility and to ensure text renders correctly for all users, embedding
 * a font subset (e.g., using open-source fonts like NotoSans) is recommended.
 * </p>
 *
 * @see Font
 * @see CJKFont
 */
public class Example_04 {

    public Example_04() throws Exception {
        // Create a new PDF document
        PDF pdf = new PDF(new BufferedOutputStream(
                new FileOutputStream("Example_04.pdf")));

        Font f0 = new Font(pdf, CoreFont.HELVETICA);
        f0.setSize(14f);

        // Create font for Traditional Chinese text
        // Uses Adobe's Ming Standard Light font (明體)
        Font f1 = new Font(pdf, CJKFont.ADOBE_MING_STD_LIGHT);
        f1.setSize(14f);

        // Create font for Simplified Chinese text
        // Uses Adobe's Heiti SC Light font (黑体-简)
        Font f2 = new Font(pdf, CJKFont.ST_HEITI_SC_LIGHT);
        f2.setSize(14f);

        // Create font for Japanese text
        // Uses Kozuka Mincho Pro VI Regular font (小塚明朝)
        Font f3 = new Font(pdf, CJKFont.KOZ_MIN_PRO_VI_REGULAR);
        f3.setSize(14f);

        // Create font for Korean text
        // Uses Adobe's Myungjo Standard Medium font (명조체)
        Font f4 = new Font(pdf, CJKFont.ADOBE_MYUNGJO_STD_MEDIUM);
        f4.setSize(14f);

        Page page = new Page(pdf, Letter.PORTRAIT);

        String fileName = "data/happy-new-year.txt";
        float x_pos = 100f;
        float y_pos = 100f;
        BufferedReader reader = new BufferedReader(
                new InputStreamReader(new FileInputStream(fileName), "UTF-8"));
        TextLine text = new TextLine(f0);
        String line = null;
        while ((line = reader.readLine()) != null) {
            text.setText(line);
            text.setLocation(x_pos, y_pos);
            text.drawOn(page);
            if (line.contains("Traditional")) {
                text.setFont(f1);
            } else if (line.contains("Simplified")) {
                text.setFont(f2);
            } else if (line.contains("Japanese")) {
                text.setFont(f3);
            } else if (line.contains("Korean")) {
                text.setFont(f4);
            } else {
                text.setFont(f0);
            }
            y_pos += 25f;
        }
        reader.close();

        pdf.complete();
    }

    public static void main(String[] args) throws Exception {
        long time0 = System.currentTimeMillis();
        new Example_04();
        long time1 = System.currentTimeMillis();
        TextUtils.printDuration("Example_04", time0, time1);
    }
}   // End of Example_04.java
