package pdfjet

type ColorCSS struct {
	transparent          uint32
	aliceblue            uint32
	antiquewhite         uint32
	aqua                 uint32
	aquamarine           uint32
	azure                uint32
	beige                uint32
	bisque               uint32
	black                uint32
	blanchedalmond       uint32
	blue                 uint32
	blueviolet           uint32
	brown                uint32
	burlywood            uint32
	cadetblue            uint32
	chartreuse           uint32
	chocolate            uint32
	coral                uint32
	cornflowerblue       uint32
	cornsilk             uint32
	crimson              uint32
	cyan                 uint32
	darkblue             uint32
	darkcyan             uint32
	darkgoldenrod        uint32
	darkgray             uint32
	darkgreen            uint32
	darkgrey             uint32
	darkkhaki            uint32
	darkmagenta          uint32
	darkolivegreen       uint32
	darkorange           uint32
	darkorchid           uint32
	darkred              uint32
	darksalmon           uint32
	darkseagreen         uint32
	darkslateblue        uint32
	darkslategray        uint32
	darkslategrey        uint32
	darkturquoise        uint32
	darkviolet           uint32
	deeppink             uint32
	deepskyblue          uint32
	dimgray              uint32
	dimgrey              uint32
	dodgerblue           uint32
	firebrick            uint32
	floralwhite          uint32
	forestgreen          uint32
	fuchsia              uint32
	gainsboro            uint32
	ghostwhite           uint32
	gold                 uint32
	goldenrod            uint32
	gray                 uint32
	green                uint32
	greenyellow          uint32
	grey                 uint32
	honeydew             uint32
	hotpink              uint32
	indianred            uint32
	indigo               uint32
	ivory                uint32
	khaki                uint32
	lavender             uint32
	lavenderblush        uint32
	lawngreen            uint32
	lemonchiffon         uint32
	lightblue            uint32
	lightcoral           uint32
	lightcyan            uint32
	lightgoldenrodyellow uint32
	lightgray            uint32
	lightgreen           uint32
	lightgrey            uint32
	lightpink            uint32
	lightsalmon          uint32
	lightseagreen        uint32
	lightskyblue         uint32
	lightslategray       uint32
	lightslategrey       uint32
	lightsteelblue       uint32
	lightyellow          uint32
	lime                 uint32
	limegreen            uint32
	linen                uint32
	magenta              uint32
	maroon               uint32
	mediumaquamarine     uint32
	mediumblue           uint32
	mediumorchid         uint32
	mediumpurple         uint32
	mediumseagreen       uint32
	mediumslateblue      uint32
	mediumspringgreen    uint32
	mediumturquoise      uint32
	mediumvioletred      uint32
	midnightblue         uint32
	mintcream            uint32
	mistyrose            uint32
	moccasin             uint32
	navajowhite          uint32
	navy                 uint32
	oldlace              uint32
	olive                uint32
	olivedrab            uint32
	orange               uint32
	orangered            uint32
	orchid               uint32
	palegoldenrod        uint32
	palegreen            uint32
	paleturquoise        uint32
	palevioletred        uint32
	papayawhip           uint32
	peachpuff            uint32
	peru                 uint32
	pink                 uint32
	plum                 uint32
	powderblue           uint32
	purple               uint32
	red                  uint32
	rosybrown            uint32
	royalblue            uint32
	saddlebrown          uint32
	salmon               uint32
	sandybrown           uint32
	seagreen             uint32
	seashell             uint32
	sienna               uint32
	silver               uint32
	skyblue              uint32
	slateblue            uint32
	slategray            uint32
	slategrey            uint32
	snow                 uint32
	springgreen          uint32
	steelblue            uint32
	tan                  uint32
	teal                 uint32
	thistle              uint32
	tomato               uint32
	turquoise            uint32
	violet               uint32
	wheat                uint32
	white                uint32
	whitesmoke           uint32
	yellow               uint32
	yellowgreen          uint32
	oldgloryred          uint32
	oldgloryblue         uint32
}
